= Ticketing support dump schema

This repository contains the json-schema describing the format of ticketing support dump defined in the CN03/GT4 group.

The schemas are available in the `schema` repository, with `schema\ticketing_support_schema.json` being the root schema.

== Using this repository

The schema is the single file `schema/ticketing_support_schema.json`. Use it with your favorite tool, or integrate
it directly in your tools.

NOTE: it could be interesting to host the schema file somewhere, which would allow users to retrieve it properly.

The official json-schema website has a list of https://json-schema.org/implementations.html#validators[validator implementations] for different programming languages. Pick your poison.

WARNING: This schema is based on json-schema draft 07, so be sure to pick an implementation that can use this draft.

=== Quickly checking the validity of a json dump

There is a python script called `quick_validate.py` that will check any json dump file against the current schema.

- Run it directly with `python quick_validate.py path/to/file.json` (same requirements as tests)
- or through https://earthly.dev/[earthly] using `earthly +validate --file path/to/file.json`

== Running tests

=== Using Docker and Earthly

Any machine with docker and https://earthly.dev/[earthly] installed can run the test suite with `earthly +test` easily.

=== Manually

==== Requirements

- Python 3.8+
- Python packages `pytest` and `jsonschema`

==== Running the tests

[source, bash]
-----
pip install pytest jsonschema
cd tests
pytest schema_tester.py
-----

== Writing new tests

Test files are themselves json files with the current schema:

[source, json]
----
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "test",
  "type": "array",
  "items": {
    "properties": {
      "schema": {
        "type": "string",
          "description": "name of the subschema detailed in the definitions of the root schema. Empty if the root schema should be used"
        },
      "input": {
        "type": "string",
        "description": "name of the input file used in the test, found in 'tests/data/input'. ie: calypso_support_minimal.json"
      },
      "expected": {
        "type": "object",
        "description": "the expected result of the test",
        "properties": {
          "result": {
            "type": "string",
            "description": "The result code of the test. 'ok' if the input is validated by the schema. 'failure' otherwise.",
            "enum": ["ok", "failure"]
          },
          "error_message": {
            "type": "string",
            "description": "The error message when the test checks for a failed validation. This is useful to verify that a rule is properly enforced, and only present when the test checks for a failed validation"
          }
        }
      }
    }
  }
}
----
